# docker-compose.yml
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - 8000:8000

  pve_server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: pve_server
    depends_on:
      - server
    ports:
      - 5000:5000

  ui:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
    ports:
      - 7700:3000
    depends_on:
      - server
      - pve_server
    environment:
      - NODE_VERSION=14.21.3
